apiVersion: v1
data:
  run: |
    #!/bin/bash
    chown root. /var/byconity /var/log/byconity
    exec "${APP_ROOT}/bin/clickhouse-server" --config "/etc/byconity/server.yaml"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: byconity
    meta.helm.sh/release-namespace: byconity
  creationTimestamp: "2024-12-06T07:42:15Z"
  labels:
    app.kubernetes.io/instance: byconity
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: byconity
    app.kubernetes.io/version: 1.16.0
    byconity-role: server
    helm.sh/chart: byconity-0.1.0
  name: byconity-server-run
  namespace: byconity
  resourceVersion: "3768"
  uid: df6ef450-1984-407f-99b9-061d44c12f7e
