apiVersion: v1
data:
  run: |
    #!/bin/bash
    exec "${APP_ROOT}/bin/daemon-manager" --config "/etc/byconity/daemon-manager.yaml"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: byconity
    meta.helm.sh/release-namespace: byconity
  creationTimestamp: "2024-12-06T07:42:15Z"
  labels:
    app.kubernetes.io/instance: byconity
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: byconity
    app.kubernetes.io/version: 1.16.0
    byconity-role: daemon-manager
    helm.sh/chart: byconity-0.1.0
  name: byconity-dm-run
  namespace: byconity
  resourceVersion: "3769"
  uid: 406facf4-de4e-4a1f-b58e-ac0ed04e5507
