apiVersion: v1
data:
  liveness: |
    #!/bin/bash
    set -euo pipefail
    QUERY_TIMEOUT=5
    timeout -k 1 "${QUERY_TIMEOUT}" clickhouse-client -h 127.0.0.1 --port "9000" --user "probe" --password "probe" --max_execution_time "$((QUERY_TIMEOUT-1))" -n -q "select 1" 2>&1
  liveness-dm: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
  liveness-rm: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
  liveness-tso: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
  poststart: |
    #!/bin/bash
    set -eo pipefail
  prestop: |-
    #!/bin/bash
    set -eo pipefail
    if [[ "${BYCONITY_ROLE}" == "worker" ]]; then
      curl --fail -X GET "http://127.0.0.1:8123/api/resource_report?action=stop"
    fi
  readiness: |
    #!/bin/bash
    set -euo pipefail
    QUERY_TIMEOUT=5
    timeout -k 1 "${QUERY_TIMEOUT}" clickhouse-client -h 127.0.0.1 --port "9000" --user "probe" --password "probe" --max_execution_time "$((QUERY_TIMEOUT-1))" -n -q "select 1" 2>&1
  readiness-dm: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
  readiness-rm: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
  readiness-tso: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: byconity
    meta.helm.sh/release-namespace: byconity
  creationTimestamp: "2024-12-06T07:42:15Z"
  labels:
    app.kubernetes.io/instance: byconity
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: byconity
    app.kubernetes.io/version: 1.16.0
    byconity-role: server
    helm.sh/chart: byconity-0.1.0
  name: byconity-lifecycle
  namespace: byconity
  resourceVersion: "3765"
  uid: 575333a0-2d36-4ec5-87fe-cb2290d602bb
