apiVersion: v1
data:
  cnch-config.yaml: |
    catalog:
      name_space: byconity
    catalog_service:
      fdb:
        cluster_file: /etc/byconity/fdb/cluster-file
      type: fdb
    cnch_type: server
    exchange_port: 9410
    exchange_status_port: 9510
    hdfs_addr: hdfs://byconity-hdfs-namenodes:8020
    http_port: 8123
    rpc_port: 8124
    service_discovery:
      cluster: default
      daemon_manager:
        headless_service: byconity-daemon-manager-headless
        psm: byconity-daemon-manager
        service: byconity-daemon-manager
      mode: dns
      resource_manager:
        headless_service: byconity-resource-manager-headless
        psm: byconity-resource-manager
        service: byconity-resource-manager
      server:
        headless_service: byconity-server-headless
        psm: byconity-server
        service: byconity-server
      tso:
        headless_service: byconity-tso-headless
        psm: byconity-tso
        service: byconity-tso
      vw: {}
    service_discovery_kv:
      resource_manager:
        expired_interval_ms: 6000
        host_path: data.cnch.resource_manager-election
        refresh_interval_ms: 1000
      server_manager:
        expired_interval_ms: 6000
        host_path: data.cnch.server-election
        refresh_interval_ms: 1000
      tso:
        expired_interval_ms: 6000
        host_path: data.cnch.tso-election
        refresh_interval_ms: 1000
    tcp_port: 9000
    tso_service:
      tso_get_leader_info_interval_ms: 0
      tso_max_retry_count: 3
      tso_window_ms: 3000
  daemon-manager.yaml: |
    catalog_service:
      fdb:
        cluster_file: /etc/byconity/fdb/cluster-file
      type: fdb
    cnch_config: /etc/byconity/cnch-config.yaml
    daemon_manager:
      daemon_jobs:
        job:
        - interval: 10000
          name: PART_GC
        - interval: 10000
          name: PART_MERGE
        - interval: 10000
          name: CONSUMER
        - interval: 5000
          name: GLOBAL_GC
        - interval: 600000
          name: TXN_GC
      http:
        port: 8123
        receive_timeout: 1800
        send_timeout: 1800
      port: 9000
      workload_thread_interval_ms: 1000
    hdfs3_config: /etc/byconity/hdfs3.xml
    listen_host: '::'
    logger:
      console: true
      count: 10
      errorlog: /var/log/byconity/daemon-manager.err.log
      level: trace
      log: /var/log/byconity/daemon-manager.log
      size: 1000M
      testlog: /var/log/byconity/daemon-manager.test.log
    path: /var/byconity
    service_discovery:
      server:
        headless_service: byconity-server-headless
        psm: byconity-server
        service: byconity-server
      tso:
        headless_service: byconity-tso-headless
        psm: byconity-tso
        service: byconity-tso
    storage_configuration:
      cnch_default_policy: cnch_default_hdfs
      disks:
        server_hdfs_disk:
          path: /var/byconity/data
          type: hdfs
        server_local_0:
          path: /var/byconity/data/
          type: local
      policies:
        cnch_default_hdfs:
          volumes:
            hdfs:
              default: server_hdfs_disk
              disk: server_hdfs_disk
        default:
          volumes:
            local:
              default: server_local_0
              disk: server_local_0
    tmp_path: /var/byconity/tmp/
  hdfs3.xml: |
    <configuration>
        <property>
            <name>dfs.client.metrics.enable</name>
            <value>true</value>
        </property>
        <property>
            <name>dfs.client.metrics.use_domain_socket</name>
            <value>true</value>
        </property>
        <property>
            <name>dfs.default.blocksize</name>
            <value>268435456</value>
        </property>
        <property>
            <name>dfs.read.hedge_read.interval_ms</name>
            <value>120</value>
        </property>
        <property>
            <name>input.connect.timeout</name>
            <value>10000</value>
        </property>
        <property>
            <name>input.read.max.retry</name>
            <value>3</value>
        </property>
        <property>
            <name>input.read.timeout</name>
            <value>6000</value>
        </property>
        <property>
            <name>input.write.timeout</name>
            <value>10000</value>
        </property>
        <property>
            <name>output.close.timeout</name>
            <value>256000</value>
        </property>
        <property>
            <name>output.connect.timeout</name>
            <value>10000</value>
        </property>
        <property>
            <name>output.default.write.retry</name>
            <value>3</value>
        </property>
        <property>
            <name>output.read.timeout</name>
            <value>120000</value>
        </property>
        <property>
            <name>output.write.timeout</name>
            <value>256000</value>
        </property>
        <property>
            <name>rpc.client.connect.retry</name>
            <value>3</value>
        </property>
        <property>
            <name>rpc.client.connect.timeout</name>
            <value>10000</value>
        </property>
        <property>
            <name>rpc.client.read.timeout</name>
            <value>20000</value>
        </property>
        <property>
            <name>rpc.client.timeout</name>
            <value>20000</value>
        </property>
        <property>
            <name>rpc.client.write.timeout</name>
            <value>20000</value>
        </property>
    </configuration>
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: byconity
    meta.helm.sh/release-namespace: byconity
  creationTimestamp: "2024-12-06T07:42:15Z"
  labels:
    app.kubernetes.io/instance: byconity
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: byconity
    app.kubernetes.io/version: 1.16.0
    byconity-role: daemon-manager
    helm.sh/chart: byconity-0.1.0
  name: byconity-dm-config
  namespace: byconity
  resourceVersion: "3775"
  uid: eb060d95-bf59-4182-a460-3f82401121da
