apiVersion: v1
data:
  run: |
    #!/bin/bash
    exec "${APP_ROOT}/bin/resource-manager" --config "/etc/byconity/resource-manager.yaml"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: byconity
    meta.helm.sh/release-namespace: byconity
  creationTimestamp: "2024-12-06T07:42:15Z"
  labels:
    app.kubernetes.io/instance: byconity
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: byconity
    app.kubernetes.io/version: 1.16.0
    byconity-role: resource-manager
    helm.sh/chart: byconity-0.1.0
  name: byconity-rm-run
  namespace: byconity
  resourceVersion: "3767"
  uid: a9a86fe2-9c79-4707-8116-cd767c825351
