apiVersion: v1
data:
  run: |
    #!/bin/bash
    exec "${APP_ROOT}/bin/tso-server" --config "/etc/byconity/tso.yaml"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: byconity
    meta.helm.sh/release-namespace: byconity
  creationTimestamp: "2024-12-06T07:42:15Z"
  labels:
    app.kubernetes.io/instance: byconity
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: byconity
    app.kubernetes.io/version: 1.16.0
    byconity-role: tso
    helm.sh/chart: byconity-0.1.0
  name: byconity-tso-run
  namespace: byconity
  resourceVersion: "3772"
  uid: 7213fc99-49bc-4526-b408-83c3902f0072
