apiVersion: v1
data:
  cnch-config.yaml: |
    catalog:
      name_space: byconity
    catalog_service:
      fdb:
        cluster_file: /etc/byconity/fdb/cluster-file
      type: fdb
    cnch_type: server
    exchange_port: 9410
    exchange_status_port: 9510
    hdfs_addr: hdfs://byconity-hdfs-namenodes:8020
    http_port: 8123
    rpc_port: 8124
    service_discovery:
      cluster: default
      daemon_manager:
        headless_service: byconity-daemon-manager-headless
        psm: byconity-daemon-manager
        service: byconity-daemon-manager
      mode: dns
      resource_manager:
        headless_service: byconity-resource-manager-headless
        psm: byconity-resource-manager
        service: byconity-resource-manager
      server:
        headless_service: byconity-server-headless
        psm: byconity-server
        service: byconity-server
      tso:
        headless_service: byconity-tso-headless
        psm: byconity-tso
        service: byconity-tso
      vw: {}
    service_discovery_kv:
      resource_manager:
        expired_interval_ms: 6000
        host_path: data.cnch.resource_manager-election
        refresh_interval_ms: 1000
      server_manager:
        expired_interval_ms: 6000
        host_path: data.cnch.server-election
        refresh_interval_ms: 1000
      tso:
        expired_interval_ms: 6000
        host_path: data.cnch.tso-election
        refresh_interval_ms: 1000
    tcp_port: 9000
    tso_service:
      tso_get_leader_info_interval_ms: 0
      tso_max_retry_count: 3
      tso_window_ms: 3000
  resource-manager.yaml: |
    catalog_service:
      fdb:
        cluster_file: /etc/byconity/fdb/cluster-file
      type: fdb
    cnch_config: /etc/byconity/cnch-config.yaml
    listen_host: '::'
    logger:
      console: true
      count: 10
      errorlog: /var/log/byconity/resource-manager.err.log
      level: trace
      log: /var/log/byconity/resource-manager.log
      size: 1000M
      testlog: /var/log/byconity/resource-manager.test.log
    resource_manager:
      http:
        port: 8123
        receive_timeout: 1800
        send_timeout: 1800
      port: 9000
      vws:
        vw:
        - name: vw_default
          num_workers: 1
          type: default
          worker_groups: ""
        - name: vw_write
          num_workers: 1
          type: write
          worker_groups: ""
    service_discovery:
      tso:
        headless_service: byconity-tso-headless
        psm: byconity-tso
        service: byconity-tso
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: byconity
    meta.helm.sh/release-namespace: byconity
  creationTimestamp: "2024-12-06T07:42:15Z"
  labels:
    app.kubernetes.io/instance: byconity
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: byconity
    app.kubernetes.io/version: 1.16.0
    byconity-role: resource-manager
    helm.sh/chart: byconity-0.1.0
  name: byconity-rm-config
  namespace: byconity
  resourceVersion: "3770"
  uid: 68c2bf2d-5050-489b-b6fe-bd8bf4df25a9
