profiles:
  default:
    exchange_timeout_ms: 300000
    load_balancing: random
    log_queries: 1
    max_execution_time: 180
quotas:
  default:
    interval:
      duration: 3600
      errors: 0
      execution_time: 0
      queries: 0
      read_rows: 0
      result_rows: 0
users:
  default:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default
  probe:
    networks:
      ip: ::/0
    password: probe
    profile: default
    quota: default
  server:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default