catalog:
  name_space: enjay

catalog_service:
  fdb:
    cluster_file: /data1/songenjie001/deploy/byconity/config/fdb/cluster-file
  type: fdb

hdfs3_config: /data1/songenjie001/deploy/byconity/config/hdfs3.xml

service_discovery:
  cluster: default
  mode: dns
  daemon_manager:
    headless_service: byconity-daemon-manager-headless
    psm: byconity-daemon-manager
    service: byconity-daemon-manager
  resource_manager:
    headless_service: byconity-resource-manager-headless
    psm: byconity-resource-manager
    service: byconity-resource-manager
  server:
    headless_service: byconity-server-headless
    psm: byconity-server
    service: byconity-server
  tso:
    headless_service: byconity-tso-headless
    psm: byconity-tso
    service: byconity-tso
  vw: {}

tso_service:
  tso_get_leader_info_interval_ms: 0
  tso_max_retry_count: 3
  tso_window_ms: 3000
  fdb:
    cluster_file: /data1/songenjie001/deploy/byconity/config/fdb/cluster-file
  http:
    port: 18123
    receive_timeout: 1800
    send_timeout: 1800
  port: 19000
  type: fdb

zookeeper: {}