catalog:
  name_space: default

catalog_service:
  fdb:
    cluster_file: /data1/songenjie001/deploy/byconity/config/fdb/fdb.cluster
  type: fdb

hdfs_addr: hdfs://127.0.0.1:8020
hdfs_user: root
hdfs3_config: /data1/songenjie001/deploy/byconity/config/hdfs3.xml

service_discovery:
  mode: local
  cluster: default
  disable_cache: 'false'
  cache_timeout: '5'
  server:
    headless_service: byconity-server-headless
    psm: byconity-server
    service: byconity-server
    node:
      host: 127.0.0.1
      hostname: 127.0.0.1
      ports:
        port:
          - name: PORT0
            value: '47124'
          - name: PORT1
            value: '48410'
          - name: PORT2
            value: '48510'
          - name: PORT3
            value: '48123'
          - name: PORT4
            value: '48000'
  tso:
    headless_service: byconity-tso-headless
    psm: byconity-tso
    service: byconity-tso
    node:
      host: 127.0.0.1
      hostname: 127.0.0.1
      ports:
        port:
          - name: PORT0
            value: '18213'
          - name: PORT1
            value: '18000'
  daemon_manager:
    headless_service: byconity-daemon-manager-headless
    psm: byconity-daemon-manager
    service: byconity-daemon-manager
    node:
      host: 127.0.0.1
      hostname: 127.0.0.1
      ports:
        port:
          - name: PORT0
            value: '38124'
          - name: PORT1
            value: '38410'
          - name: PORT2
            value: '38510'
          - name: PORT3
            value: '38123'
          - name: PORT4
            value: '38000'
  resource_manager:
    headless_service: byconity-resource-manager-headless
    psm: byconity-resource-manager
    service: byconity-resource-manager
    node:
      host: 127.0.0.1
      hostname: 127.0.0.1
      ports:
        port:
          - name: PORT0
            value: '28124'
          - name: PORT1
            value: '28410'
          - name: PORT2
            value: '28510'
          - name: PORT3
            value: '28123'
          - name: PORT4
            value: '28000'
  vw:
    psm: byconity-vw

tso_service:
  tso_get_leader_info_interval_ms: 0
  tso_max_retry_count: 3
  tso_window_ms: 3000
  fdb:
    cluster_file: /data1/songenjie001/deploy/byconity/config/fdb/fdb.cluster
  http:
    port: 18123
    receive_timeout: 1800
    send_timeout: 1800
  port: 18000
  type: fdb
