apiVersion: v1
kind: Service
metadata:
  name: {{ include "byconity.fullname" . }}-server
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: server
spec:
  selector:
    k8s-app: kubernetes-dashboard
  type: ClusterIP
  selector:
    {{- include "byconity.selectorLabels" . | nindent 4 }}
    byconity-role: server
  ports:
    - name: port0
      port: {{ $.Values.byconity.ports.tcp }}
      targetPort: tcp
    - name: port1
      port: {{ $.Values.byconity.ports.rpc }}
      targetPort: rpc
    - name: port2
      port: {{ $.Values.byconity.ports.http }}
      targetPort: http
    - name: port3
      port: {{ $.Values.byconity.ports.tcpSecure }}
      targetPort: tcp-secure
    - name: port4
      port: {{ $.Values.byconity.ports.https }}
      targetPort: https
    - name: port5
      port: {{ $.Values.byconity.ports.exchange }}
      targetPort: exchange
    - name: port6
      port: {{ $.Values.byconity.ports.exchangeStatus }}
      targetPort: exchange-status

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "byconity.fullname" . }}-server-headless
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: server
spec:
  type: ClusterIP
  clusterIP: None
  #type: NodePort
  selector:
    {{- include "byconity.selectorLabels" . | nindent 4 }}
    byconity-role: server
  ports:
    - name: port0
      port: {{ $.Values.byconity.ports.tcp }}
      targetPort: tcp
    - name: port1
      port: {{ $.Values.byconity.ports.rpc }}
      targetPort: rpc
    - name: port2
      port: {{ $.Values.byconity.ports.http }}
      targetPort: http
    - name: port3
      port: {{ $.Values.byconity.ports.tcpSecure }}
      targetPort: tcp-secure
    - name: port4
      port: {{ $.Values.byconity.ports.https }}
      targetPort: https
    - name: port5
      port: {{ $.Values.byconity.ports.exchange }}
      targetPort: exchange
    - name: port6
      port: {{ $.Values.byconity.ports.exchangeStatus }}
      targetPort: exchange-status

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "byconity.fullname" . }}-server-connector
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: server
spec:
  type: NodePort
  selector:
    {{- include "byconity.selectorLabels" . | nindent 4 }}
    byconity-role: server
  ports:
    - name: port0
      port: {{ $.Values.byconity.ports.tcp }}
      targetPort: tcp
      nodePort: 32200
    - name: port1
      port: {{ $.Values.byconity.ports.rpc }}
      targetPort: rpc
    - name: port2
      port: {{ $.Values.byconity.ports.http }}
      targetPort: http
    - name: port3
      port: {{ $.Values.byconity.ports.tcpSecure }}
      targetPort: tcp-secure
    - name: port4
      port: {{ $.Values.byconity.ports.https }}
      targetPort: https
    - name: port5
      port: {{ $.Values.byconity.ports.exchange }}
      targetPort: exchange
    - name: port6
      port: {{ $.Values.byconity.ports.exchangeStatus }}
      targetPort: exchange-status
