# Default values for byconity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# please replace  storageClassName
nameOverride: ""
fullnameOverride: ""

image:
  repository: byconity/byconity
  tag: stable
  imagePullPolicy: IfNotPresent

byconity:
  hdfs_address: hdfs://master:8020 
  use_existing_fdb: true
  fdb_cluster_file: 4500
  hdfs3Config:
    dfs.client.metrics.enable: true
    dfs.client.metrics.use_domain_socket: true
    dfs.default.blocksize: "268435456"
    dfs.read.hedge_read.interval_ms: 120
    input.connect.timeout: 10000
    input.read.max.retry: 3
    input.read.timeout: 6000
    input.write.timeout: 10000
    output.close.timeout: 256000
    output.connect.timeout: 10000
    output.default.write.retry: 3
    output.read.timeout: 120000
    output.write.timeout: 256000
    rpc.client.connect.retry: 3
    rpc.client.connect.timeout: 10000
    rpc.client.read.timeout: 20000
    rpc.client.timeout: 20000
    rpc.client.write.timeout: 20000

  configOverwrite:
    storage_configuration:
      cnch_default_policy: cnch_default_hdfs
      disks:
        server_hdfs_disk:
          path: /var/byconity/data
          type: hdfs
        server_local_0:
          path: /var/byconity/data
          type: local

      policies:
        cnch_default_hdfs:
          volumes:
            hdfs:
              default: server_hdfs_disk
              disk: server_hdfs_disk
        default:
          volumes:
            local:
              default: server_local_0
              disk: server_local_0

  ports:
    tcp: 9000
    http: 8123
    rpc: 8124
    tcpSecure: 9100
    https: 9123
    exchange: 9410
    exchangeStatus: 9510

  usersOverwrite:
    users:
      default:
        password: ""
      probe:
        password: probe

  server:
    replicas: 3
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          #storageClassName: local-path #replace to your storageClassName
    configOverwrite:
      logger:
        level: trace
      disk_cache_strategies:
        simple:
          lru_max_size: 429496729600 # 400Gi
      timezone: Asia/Shanghai

  tso:
    replicas: 1
    image: ""
    podAnnotations: { }
    resources:
      limits:
        cpu: "10"  # >=3
        memory: 20Gi
      requests:
        cpu: "10"  # >=3
        memory: 20Gi
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    additionalVolumeClaimTemplates:   #add new pvc for coordination
      - metadata:
          name: coordination
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          #storageClassName: local-path #replace to your storageClassName

    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          #storageClassName: local-path #replace to your storageClassName
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          #storageClassName: local-path #replace to your storageClassName
    additionalVolumes:    #add new volume for coordination
      volumes:
      volumeMounts:
        - name: coordination
          mountPath: /var/byconity/tso/coordination
    configOverwrite: { }


  daemonManager:
    replicas: 1 # Please keep single instance now, daemon manager HA is WIP
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    configOverwrite: { }

  resourceManager:
    replicas: 1
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    configOverwrite: { }

  defaultWorker: &defaultWorker
    replicas: 6
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Gi
          #storageClassName: local-path #replace to your storageClassName
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          #storageClassName: local-path #replace to your storageClassName
    configOverwrite:
      logger:
        level: trace
      disk_cache_strategies:
        simple:
          lru_max_size: 429496729600 # 400Gi
      timezone: Asia/Shanghai

  virtualWarehouses:
    - <<: *defaultWorker
      name: vw_default
      replicas: 6
    - <<: *defaultWorker
      name: vw_write
      replicas: 5

  commonEnvs:
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: "metadata.name"
    - name: MY_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.uid"
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: "status.podIP"
    - name: MY_HOST_IP
      valueFrom:
        fieldRef:
          # fieldPath: "status.hostIP"
          fieldPath: "status.podIP"
    - name: CONSUL_HTTP_HOST
      valueFrom:
        fieldRef:
          fieldPath: "status.hostIP"

  additionalEnvs: [ ]

  additionalVolumes:
    volumes: [ ]
    volumeMounts: [ ]

  postStart: ""
  preStop: ""
  readiness: ""
  liveness: ""

  ingress:
    enabled: false
    className: ""
    annotations: { }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: byconity-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [ ]


